# Node docker image on which this would be run
image: node:latest

#This command is run before actual stages start running
before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - npm install

stages:
  - test
  # - deploy

# lint and test are two different jobs in the same stage.
# This allows us to run these two in parallel and making build faster

# Job 1:
lint:
  stage: test
  script:
    - npm run lint

# deployToAWS:
#   only:
#     # - master
#     - developer
#   stage: deploy
#   script:
#     - bash deploy.sh
